apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: sample-k8s-gateway-api
build:
  tagPolicy:
    envTemplate:
      template: "latest"
  artifacts:
    - image: sample-k8s-gateway-api/api
      context: ./api
  local:
    push: false
    useBuildkit: true
profiles:
  - name: local
    activation:
      - env: ENV=local
      - kubeContext: minikube
        command: dev
    manifests:
      kustomize:
        paths:
          - ./.k8s/overlays/local
    deploy:
      kubectl: {}
