resources:
  - ../../base
  - namespace.yaml
patches:
  - target:
      kind: ConfigMap
    path: api/configmap.yaml
helmCharts:
  - name: base
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.18.0
    namespace: istio-system
  - name: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: 1.18.0
    namespace: istio-system
